#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$config = require __DIR__ . '/config/app.php';
date_default_timezone_set($config['timezone']);

use App\Commands\CommandRunner;

exit((new CommandRunner())->run(array_slice($argv, 1)));
